# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      dev-deps: { dependency-type: development }
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      gh-actions: { patterns: ["*"] }

  - package-ecosystem: npm
    directory: "/node-version"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      dev-deps: { dependency-type: development }
  - package-ecosystem: github-actions
    directory: "/node-version"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      gh-actions: { patterns: ["*"] }

  - package-ecosystem: npm
    directory: "/setup-nodenv"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      dev-deps: { dependency-type: development }
  - package-ecosystem: github-actions
    directory: "/setup-nodenv"
    schedule: { interval: weekly }
    cooldown: { default-days: 15 }
    groups:
      gh-actions: { patterns: ["*"] }
