# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "monthly" }
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "monthly" }
  - package-ecosystem: "github-actions"
    directory: "/node-version"
    schedule: { interval: "monthly" }
  - package-ecosystem: "npm"
    directory: "/node-version"
    schedule: { interval: "monthly" }
  - package-ecosystem: "github-actions"
    directory: "/setup-nodenv"
    schedule: { interval: "monthly" }
  - package-ecosystem: "npm"
    directory: "/setup-nodenv"
    schedule: { interval: "monthly" }
