#!/usr/bin/env bash
set -euo pipefail

if [ master != "$(git symbolic-ref --short HEAD)" ]; then
  >&2 echo "Aborting: Not currently on master branch"
  exit 1
fi

actions=${npm_package_actions:-$(node -p "require('./package').actions")}

>&2 echo "Pushing master with tags"
git push --follow-tags

for action in ${actions:?}; do
  remote="https://github.com/nodenv/actions-$action.git"

  >&2 echo "Pushing subtree master: $action"
  git subtree push --prefix="$action" "$remote" master
done
