#!/usr/bin/env bash
set -euo pipefail

if [ master != "$(git symbolic-ref --short HEAD)" ]; then
  echo "Aborting: Not currently on master branch" >&2
  exit 1
fi

git push

for action in node-version setup-nodenv; do
  remote="https://github.com/nodenv/actions-$action.git"
  git subtree push --prefix="$action" "$remote" master
done
