#!/usr/bin/env bash
set -euo pipefail

if [ master != "$(git symbolic-ref --short HEAD)" ]; then
  >&2 echo "Aborting: Not currently on master branch"
  >&2 echo "(tag-deletion likely required)"
  exit 1
fi

# take version param; fallback to npm env var; fallback to asking git
version=${1:-${npm_package_version:-$(git describe --tags --match 'v[[:digit:]]*')}}
version=${version%%.*} # strip all but major
branch=v${version#v} # ensure 'v' prefix

script/push-masters

>&2 echo "Pushing to major-version branch: $branch"
git push https://github.com/nodenv/actions master:"$branch"

for action in node-version setup-nodenv; do
  remote="https://github.com/nodenv/actions-$action.git"

  >&2 echo "Pushing subtree major-version: $action $branch"
  git subtree push --prefix="$action" "$remote" "${branch:?}"
done
