name: Release
on:
  push: { tags: "v*.*.*" }
  workflow_dispatch:
  workflow_call:

permissions: {}
jobs:
  release:
    uses: nodenv/.github/.github/workflows/release.yml@bd27009d5f178c0a88d42f7b07e6a3c7623ed768 # v7.0.8
    permissions: { contents: write, id-token: write }
    with: { homebrew: false, npm: false }

  sync:
    uses: nodenv/.github/.github/workflows/sync-major-version.yml@bd27009d5f178c0a88d42f7b07e6a3c7623ed768 # v7.0.8
    permissions: { contents: write }
