name: Sync Repos
on:
  push:
    branches: main
    tags: "v.*"
  workflow_call:
  workflow_dispatch:

permissions:
  actions: write # allow pushing workflow files to subtree repos
  contents: write

jobs:
  subtrees:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: [node-version, setup-nodenv]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch full history to replay in subtree
          # token: ${{secrets.BOT_TOKEN}} # persisted for subsequent git operations
      - run: |
          split_head=$(git subtree split --prefix ${{matrix.action}})
          git push $remote ${split_head:?}:${{github.ref}}
        env:
          remote: https://github.com/${{github.repository}}-${{matrix.action}}
